version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/workspace
    container_name: mlops_app
    env_file:
      - .env
    command: tail -f /dev/null
    healthcheck:
      test: ["CMD-SHELL", "git --version && python --version"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
